version: '3.8'

services:
  # 📊 Prometheus - Metrics Collection
  prometheus:
    image: prom/prometheus:latest
    container_name: life-eval-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - monitoring

  # 📈 Grafana - Visualization Dashboard
  grafana:
    image: grafana/grafana:latest
    container_name: life-eval-grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=cosmic_truth_scanner_2024
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - monitoring

  # 🔍 Loki - Log Aggregation
  loki:
    image: grafana/loki:latest
    container_name: life-eval-loki
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki.yml:/etc/loki/local-config.yaml
      - loki_data:/tmp/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring

  # 📋 Promtail - Log Collection
  promtail:
    image: grafana/promtail:latest
    container_name: life-eval-promtail
    volumes:
      - ./monitoring/promtail.yml:/etc/promtail/config.yml
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitoring

  # 🚨 AlertManager - Alert Handling
  alertmanager:
    image: prom/alertmanager:latest
    container_name: life-eval-alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=http://localhost:9093'
    networks:
      - monitoring

  # 📊 Node Exporter - System Metrics
  node-exporter:
    image: prom/node-exporter:latest
    container_name: life-eval-node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - monitoring

  # 📊 cAdvisor - Container Metrics
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: life-eval-cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    devices:
      - /dev/kmsg
    networks:
      - monitoring

  # 🤖 AI Response Quality Monitor
  ai-quality-monitor:
    build:
      context: .
      dockerfile: monitoring/Dockerfile.ai-monitor
    container_name: life-eval-ai-monitor
    environment:
      - API_BASE_URL=http://api:8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PROMETHEUS_PORT=8000
    ports:
      - "8001:8000"
    volumes:
      - ./monitoring:/app/monitoring
    networks:
      - monitoring
      - default
    depends_on:
      - prometheus

  # 🎨 Visual Performance Monitor
  visual-monitor:
    build:
      context: .
      dockerfile: monitoring/Dockerfile.visual-monitor
    container_name: life-eval-visual-monitor
    environment:
      - FRONTEND_URL=http://frontend:3000
      - PROMETHEUS_PORT=8000
    ports:
      - "8002:8000"
    volumes:
      - ./monitoring:/app/monitoring
    networks:
      - monitoring
      - default
    depends_on:
      - prometheus

volumes:
  prometheus_data:
  grafana_data:
  loki_data:
  alertmanager_data:

networks:
  monitoring:
    driver: bridge
  default:
    external: true
    name: life-evaluation-api_default