# Prometheus Configuration for Life Evaluation API
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alert_rules.yml"

# Scrape configuration
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API Server Metrics
  - job_name: 'life-eval-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Frontend Performance Metrics
  - job_name: 'life-eval-frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # System Metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Container Metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Database Metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'

  # AI Quality Monitor
  - job_name: 'ai-quality-monitor'
    static_configs:
      - targets: ['ai-quality-monitor:8000']
    scrape_interval: 30s

  # Visual Performance Monitor
  - job_name: 'visual-monitor'
    static_configs:
      - targets: ['visual-monitor:8000']
    scrape_interval: 60s

  # OpenAI API Performance (via proxy)
  - job_name: 'openai-proxy'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/openai-metrics'
    scrape_interval: 30s